[config]
schemaVersion = "1.1.51"

[general]
repository = "https://thunderstore.io"

[package]
description = "Adds the Shy Guy (SCP-096) to Lethal Company. Fully custom animations and behavior. Model from SCP: Containment Breach."
websiteUrl = "https://github.com/theunknowncod3r/Scopophobia"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.15.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/Scopophobia.dll"
target = "plugins/Scopophobia/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/scp096"
target = "plugins/scopophobia/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]